version: '3.8'

services:
  api:
    image: ghcr.io/OWNER/REPO-api:latest  # This will be replaced by GitHub Actions
    container_name: scarlet-vertigo-api
    ports:
      - "3031:3031"
    environment:
      - PORT=3031
      - DATABASE_URL=mongodb://mongo:27017/scarlet-vertigo-db?replicaSet=rs0
      - JWT_SECRET=your-production-jwt-secret-key-change-this-2024
      - ACCESS_TOKEN_VALIDITY_DURATION_IN_SEC=86400
      - NODE_ENV=production
    networks:
      - default
      - mongo_network
    restart: always

  dashboard:
    image: ghcr.io/OWNER/REPO-dashboard:latest  # This will be replaced by GitHub Actions
    container_name: scarlet-vertigo-dashboard
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NEXT_PUBLIC_API_URL=http://193.180.211.65:3031
    depends_on:
      - api
    restart: always

  frontend:
    image: ghcr.io/OWNER/REPO-frontend:latest  # This will be replaced by GitHub Actions
    container_name: scarlet-vertigo-frontend
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NEXT_PUBLIC_API_URL=http://193.180.211.65:3031
    depends_on:
      - api
    restart: always

networks:
  mongo_network:
    external: true
    name: mongo-docker_backend-net