name: Build and Deploy Docker Images

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:
        inputs:
            force_build_all:
                description: 'Force build all applications'
                required: false
                default: 'false'
                type: boolean

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    changes:
        runs-on: ubuntu-latest
        outputs:
            api: ${{ steps.changes.outputs.api }}
            dashboard: ${{ steps.changes.outputs.dashboard }}
            scarlet-frontend: ${{ steps.changes.outputs.scarlet-frontend }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Check for changes
              uses: dorny/paths-filter@v2
              id: changes
              with:
                  filters: |
                      api:
                        - 'apps/api/**'
                        - 'packages/**'
                        - 'package.json'
                        - 'turbo.json'
                      dashboard:
                        - 'apps/dashboard/**'
                        - 'packages/**'
                        - 'package.json'
                        - 'turbo.json'
                      scarlet-frontend:
                        - 'apps/scarlet-frontend/**'
                        - 'packages/**'
                        - 'package.json'
                        - 'turbo.json'

    build-api:
        needs: changes
        if: needs.changes.outputs.api == 'true' || github.event_name == 'workflow_dispatch' || github.event.inputs.force_build_all == 'true'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Log in to Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=sha,prefix=commit-
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./apps/api/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

    build-dashboard:
        needs: changes
        if: needs.changes.outputs.dashboard == 'true' || github.event_name == 'workflow_dispatch' || github.event.inputs.force_build_all == 'true'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Log in to Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-dashboard
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=sha,prefix=commit-
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./apps/dashboard/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

    build-scarlet-frontend:
        needs: changes
        if: needs.changes.outputs.scarlet-frontend == 'true' || github.event_name == 'workflow_dispatch' || github.event.inputs.force_build_all == 'true'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Log in to Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-scarlet-frontend
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=sha,prefix=commit-
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./apps/scarlet-frontend/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
